### ISSUE TITLE
Where are template destinationions defined?

### ISSUE THREAD

**Issue by 97-109-107** [s-ol/themer#20]
If I wanted to add a new template to be compiled along with the default ones, I figure I could go ahead and add it here and create the appropriate template.

```
files:
  xresources.tpl: Xresources
  index.tpl: index.html
  i3status.tpl: i3status.conf
  i3.tpl: i3.conf
  new.tpl: new.conf
```

What I'm unsure about is how where do I define where `new.conf` should be placed after rendering.
